erDiagram
    User ||--|{ Profile : "has"
    User ||--|{ CustomerProject : "manages"
    CustomerProject ||--|{ TenantEndpoint : "has"

    User {
        int id PK
        string email UK
        string name
    }
    Profile {
        int id PK
        string theme "e.g., 'light' or 'dark'"
        int userId FK
    }
    CustomerProject {
        int id PK
        string name
        json piiFields "['user.email', 'user.address']"
        int userId FK
    }
    TenantEndpoint {
        int id PK
        string name "e.g., 'Development', 'Production'"
        string host "https://api.customer-dev.com"
        string type "DEV, TEST, PROD"
        int customerProjectId FK
    }    
    SavedApiCall {
        int id PK
        string name
        string description
        json payload
        json headers
        int tenantEndpointId FK
    }

